input:
  H3K4me3:
    P25_GFP+:
      seurat_object: inputs/H3K4me3/01.clustering/Seurat_5000_UMI.Rds
      fragments:     inputs/H3K4me3/fragments/fragments.tsv.gz
      peaks:         inputs/H3K4me3/macs/macs2_peaks.combined/broad/combined_peaks.broadPeak
    P15_GFP+:
      seurat_object: inputs/H3K4me3_P15_GFP_positive/01.clustering/Seurat_5000_UMI.Rds
      fragments:     inputs/H3K4me3_P15_GFP_positive/fragments/fragments.tsv.gz
      peaks:         inputs/H3K4me3_P15_GFP_positive/macs/macs2_peaks.combined/broad/combined_peaks.broadPeak
    P15_GFP-:
      seurat_object: inputs/H3K4me3_P15_GFP_negative/01.clustering/Seurat_5000_UMI.Rds
      fragments:     inputs/H3K4me3_P15_GFP_negative/fragments/fragments.tsv.gz
      peaks:         inputs/H3K4me3_P15_GFP_negative/macs/macs2_peaks.combined/broad/combined_peaks.broadPeak
  H3K27me3:
    P25_GFP+:
      seurat_object: inputs/H3K27me3/01.clustering/Seurat_5000_UMI.Rds
      fragments:     inputs/H3K27me3/fragments/fragments.tsv.gz
      peaks:         inputs/H3K27me3/macs/macs2_peaks.combined/broad/combined_peaks.broadPeak
    P15_GFP+:
      seurat_object: inputs/H3K27me3_P15_GFP_positive/01.clustering/Seurat_5000_UMI.Rds
      fragments:     inputs/H3K27me3_P15_GFP_positive/fragments/fragments.tsv.gz
      peaks:         inputs/H3K27me3_P15_GFP_positive/macs/macs2_peaks.combined/broad/combined_peaks.broadPeak
    P15_GFP-:
      seurat_object: inputs/H3K27me3_P15_GFP_negative/01.clustering/Seurat_5000_UMI.Rds
      fragments:     inputs/H3K27me3_P15_GFP_negative/fragments/fragments.tsv.gz
      peaks:         inputs/H3K27me3_P15_GFP_negative/macs/macs2_peaks.combined/broad/combined_peaks.broadPeak
  H3K27ac:
    P25_GFP+:
      seurat_object: inputs/H3K27ac/01.clustering/Seurat_5000_UMI.Rds
      fragments:     inputs/H3K27ac/fragments/fragments.tsv.gz
      peaks:         inputs/H3K27ac/macs/macs2_peaks.combined/broad/combined_peaks.broadPeak

  Sox10_RNA:
    # Output from cellranger
    replicate1:    inputs/Sox10_RNA/rep1/filtered_feature_bc_matrix
    replicate2:    inputs/Sox10_RNA/rep2/filtered_feature_bc_matrix
  Sten_RNA:
    # Loom file from Linnarsson web
    loom_file:     inputs/Sten_RNA/l5_all.loom