samples:
  H3K4me3_N1: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_005
    clustering_params: 
      min_reads_log10: 3.7
      max_reads_log10: 5.5
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
  H3K4me3_N2: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_009
    clustering_params: 
      min_reads_log10: 3.7
      max_reads_log10: 5.5
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P25
  H3K4me3_N3: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_20_MB1
    clustering_params: 
      min_reads_log10: 2.5
      max_reads_log10: 4.2
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP+
    Age: P15
  H3K4me3_N4: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_20_MB2
    clustering_params: 
      min_reads_log10: 2.5
      max_reads_log10: 4.2
      min_peaks_ratio: 0.5
      max_peaks_ratio: 0.98
    GFP: GFP-
    Age: P15
        
  
  H3K27me3_N1: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_19_003
    clustering_params: 
      min_reads_log10: 4
      max_reads_log10: 5.6
      min_peaks_ratio: 0.25
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25
  H3K27me3_N2: 
    cellranger_out: /data/proj/GCB_MB/CT/CT_20_006
    clustering_params: 
      min_reads_log10: 4
      max_reads_log10: 5.6
      min_peaks_ratio: 0.25
      max_peaks_ratio: 0.75
    GFP: GFP+
    Age: P25

general:
  clustering_window: [250,1000,5000,25000,100000]
